[versions]
pluginPublish = "1.3.1"
jib = "0.28.1"
guava = "32.1.2-jre"
jackson = "2.21.0"
axionRelease = "1.21.1"

[libraries]
jibCore = { module = "com.google.cloud.tools:jib-core", version.ref = "jib" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
jacksonDatabind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }

[plugins]
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish" }
axionRelease = { id = "pl.allegro.tech.build.axion-release", version.ref = "axionRelease" }
